default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chat_api_development

test:
  <<: *default
  database: chat_api_test

production:
  <<: *default
  database: chat_api_production
  username: <%= ENV["SPACE_CODE_DATABASE_USERNAME"] %>
  password: <%= ENV["SPACE_CODE_DATABASE_PASSWORD"] %>
